<?php

declare(strict_types=1);

namespace UsinaDocs\Core;

use Dotenv\Dotenv;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Factory\AppFactory as SlimAppFactory;
use Slim\Views\Twig;
use UsinaDocs\Core\Content\PublishedPageRepository;
use UsinaDocs\Core\Infrastructure\Database;
use UsinaDocs\Core\Authentication\Authenticator;
use UsinaDocs\Core\Content\EditorialService;
use UsinaDocs\Core\Content\ReusableArtifactService;
use UsinaDocs\Core\Content\ContentPackageService;
use UsinaDocs\Core\Media\MediaLibrary;

final class AppFactory
{
    public static function create(string $root, ?string $databasePath = null): \Slim\App
    {
        Dotenv::createImmutable($root)->safeLoad();
        if ($databasePath === null) {
            $configuredPath = $_ENV['USINADOCS_DB_PATH'] ?? 'database/database.sqlite';
            $isAbsolute = str_starts_with($configuredPath, DIRECTORY_SEPARATOR) || preg_match('/^[A-Za-z]:[\\\\\/]/', $configuredPath) === 1;
            $databasePath = $isAbsolute ? $configuredPath : $root.DIRECTORY_SEPARATOR.$configuredPath;
        }

        $database = Database::connect($databasePath);
        $repository = new PublishedPageRepository($database);
        $authenticator = new Authenticator($database);
        $editorial = new EditorialService($database);
        $artifacts = new ReusableArtifactService($database);
        $packages = new ContentPackageService($database);
        $media = new MediaLibrary($database, $root.'/storage/media');
        $twig = Twig::create($root.'/templates', ['cache' => false]);
        $app = SlimAppFactory::create();
        $app->addErrorMiddleware(true, true, true);
        $app->addBodyParsingMiddleware();
        if (session_status() !== PHP_SESSION_ACTIVE) session_start();

        $app->get('/', static function (ServerRequestInterface $request, ResponseInterface $response): ResponseInterface {
            return $response->withHeader('Location', '/pt/p/bem-vindo')->withStatus(302);
        });
        $app->get('/favicon.ico', static function (ServerRequestInterface $request, ResponseInterface $response): ResponseInterface {
            return $response->withStatus(204);
        });
        $app->get('/media/{id}', static function ($request,$response,array $a) use ($media) { $item=$media->find($a['id']);if($item===null||!is_file($media->path($item)))return$response->withStatus(404);$stream=fopen($media->path($item),'rb');$response->getBody()->write((string)stream_get_contents($stream));fclose($stream);return$response->withHeader('Content-Type',$item['mime_type'])->withHeader('Content-Length',(string)$item['byte_size']);});

        $app->get('/{locale}/p/{slug}', static function (ServerRequestInterface $request, ResponseInterface $response, array $arguments) use ($repository, $twig): ResponseInterface {
            $page = $repository->findByLocalizedSlug((string) $arguments['locale'], (string) $arguments['slug']);

            if ($page === null) {
                $response->getBody()->write('Page not found.');

                return $response->withStatus(404);
            }

            $canEdit = isset($_SESSION['user']) && $_SESSION['user']['role'] === 'administrator';
            return $twig->render($response, 'page.twig', ['page' => $page, 'can_edit' => $canEdit]);
        });
        $app->get('/login', static fn (ServerRequestInterface $request, ResponseInterface $response): ResponseInterface => $twig->render($response, 'login.twig'));
        $app->post('/login', static function (ServerRequestInterface $request, ResponseInterface $response) use ($authenticator): ResponseInterface {
            $data = (array) $request->getParsedBody(); $user = $authenticator->attempt((string)($data['email'] ?? ''), (string)($data['password'] ?? ''));
            if ($user === null) return $response->withHeader('Location', '/login')->withStatus(302);
            session_regenerate_id(true); $_SESSION['user'] = $user; return $response->withHeader('Location', '/admin')->withStatus(302);
        });
        $app->post('/logout', static function (ServerRequestInterface $request, ResponseInterface $response): ResponseInterface { $_SESSION = []; session_destroy(); return $response->withHeader('Location', '/')->withStatus(302); });
        $app->get('/admin', static function (ServerRequestInterface $request, ResponseInterface $response) use ($twig, $editorial): ResponseInterface {
            if (!isset($_SESSION['user']) || $_SESSION['user']['role'] !== 'administrator') return $response->withHeader('Location', '/login')->withStatus(302);
            $search=(string)($request->getQueryParams()['q']??'');return $twig->render($response, 'admin.twig', ['user' => $_SESSION['user'], 'catalog'=>$editorial->catalog($search),'search'=>$search]);
        });
        $app->get('/admin/translations', static function (ServerRequestInterface $request, ResponseInterface $response) use ($twig, $editorial,$artifacts): ResponseInterface {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$search=(string)($request->getQueryParams()['q']??'');return$twig->render($response,'translation-review.twig',['pages'=>$editorial->translationReview($search),'artifacts'=>$artifacts->translationReview($search),'search'=>$search]);});
        $app->get('/admin/packages', static function ($request,$response) use ($twig) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);return$twig->render($response,'packages.twig');});
        $app->post('/admin/packages/preview', static function (ServerRequestInterface $request,ResponseInterface $response) use ($twig,$packages) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$file=$request->getUploadedFiles()['package']??null;if($file===null||$file->getError()!==UPLOAD_ERR_OK)return$twig->render($response,'packages.twig',['error'=>'Selecione um pacote ZIP válido.'])->withStatus(422);$content=(string)$file->getStream()->getContents();$preview=$packages->preview($content);$token=null;if($preview['valid']&&$preview['summary']['slug_conflicts']===0&&$preview['summary']['route_changes']===0&&$preview['summary']['unknown_blocks']===0){$token=bin2hex(random_bytes(16));$path=tempnam(sys_get_temp_dir(),'usinadocs-import-');if($path!==false){file_put_contents($path,$content);$_SESSION['package_previews'][$token]=$path;}}return$twig->render($response,'packages.twig',['preview'=>$preview,'filename'=>$file->getClientFilename(),'token'=>$token]);});
        $app->post('/admin/packages/import', static function (ServerRequestInterface $request,ResponseInterface $response) use ($twig,$packages) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$data=(array)$request->getParsedBody();$token=(string)($data['token']??'');$strategy=(string)($data['strategy']??'create_only');$path=$_SESSION['package_previews'][$token]??null;unset($_SESSION['package_previews'][$token]);$resolved=is_string($path)?realpath($path):false;$temporary=realpath(sys_get_temp_dir());if($resolved===false||$temporary===false||!str_starts_with($resolved,$temporary.DIRECTORY_SEPARATOR)||!is_file($resolved))return$twig->render($response,'packages.twig',['error'=>'A prévia expirou. Envie o pacote novamente.'])->withStatus(422);try{$result=$packages->import((string)file_get_contents($resolved),$strategy);}finally{@unlink($resolved);}return$twig->render($response,'packages.twig',['result'=>$result]);});
        $app->get('/admin/pages/{id}/export', static function ($request,$response,array $a) use ($packages) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$package=$packages->exportPublishedPage($a['id']);if($package===null)return$response->withStatus(404);$response->getBody()->write($package['content']);return$response->withHeader('Content-Type','application/zip')->withHeader('Content-Disposition','attachment; filename="'.$package['filename'].'"')->withHeader('Content-Length',(string)strlen($package['content']));});
        $app->get('/admin/models', static function ($request,$response) use ($twig,$editorial) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);return$twig->render($response,'models.twig',['models'=>$editorial->editorialModels()]);});
        $app->get('/admin/models/new', static function ($request,$response) use ($twig) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);return$twig->render($response,'model-form.twig',['artifacts'=>[['type'=>'text','label'=>'Texto','required'=>true]]]);});
        $app->post('/admin/models', static function (ServerRequestInterface $request,ResponseInterface $response) use ($editorial) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$data=(array)$request->getParsedBody();$artifacts=json_decode((string)($data['artifacts_json']??'[]'),true);$id=$editorial->createEditorialModel((string)($data['content_type']??''),trim((string)($data['label']??'')),trim((string)($data['description']??'')),is_array($artifacts)?$artifacts:[]);return$response->withHeader('Location','/admin/models/'.$id.'/edit')->withStatus(302);});
        $app->post('/admin/models/{id}/revisions', static function ($request,$response,array $arguments) use ($editorial) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$editorial->createEditorialModelRevision($arguments['id']);return$response->withHeader('Location','/admin/models/'.$arguments['id'].'/edit')->withStatus(302);});
        $app->get('/admin/models/{id}/edit', static function ($request,$response,array $arguments) use ($twig,$editorial) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$model=$editorial->editorialModelDraft($arguments['id']);if($model===null)return$response->withStatus(404);return$twig->render($response,'model-form.twig',['model'=>$model,'artifacts'=>$model['artifacts']]);});
        $app->post('/admin/models/{id}', static function (ServerRequestInterface $request,ResponseInterface $response,array $arguments) use ($editorial) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$data=(array)$request->getParsedBody();$artifacts=json_decode((string)($data['artifacts_json']??'[]'),true);$editorial->updateEditorialModelDraft($arguments['id'],trim((string)($data['label']??'')),trim((string)($data['description']??'')),is_array($artifacts)?$artifacts:[]);return$response->withHeader('Location','/admin/models')->withStatus(302);});
        $app->post('/admin/models/{id}/publish', static function ($request,$response,array $arguments) use ($editorial) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$editorial->publishEditorialModel($arguments['id']);return$response->withHeader('Location','/admin/models')->withStatus(302);});
        $app->get('/admin/models/{id}/history', static function ($request,$response,array $a) use ($editorial,$twig) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$history=$editorial->editorialModelHistory($a['id']);if($history===[])return$response->withStatus(404);$current=array_values(array_filter($history,static fn(array $revision):bool=>$revision['is_current']));return$twig->render($response,'model-history.twig',['model_id'=>$a['id'],'history'=>$history,'current'=>$current[0]??null]);});
        $app->get('/admin/models/{id}/compare', static function ($request,$response,array $a) use ($editorial,$twig) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$q=$request->getQueryParams();$comparison=$editorial->compareEditorialModelRevisions($a['id'],(string)($q['from']??''),(string)($q['to']??''));if($comparison===null)return$response->withStatus(404);return$twig->render($response,'model-comparison.twig',['model_id'=>$a['id'],'comparison'=>$comparison]);});
        $app->post('/admin/models/{id}/restore/{revision}', static function ($request,$response,array $a) use ($editorial) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$id=$editorial->restoreEditorialModelRevision($a['id'],$a['revision']);return$response->withHeader('Location',$id?'/admin/models/'.$a['id'].'/edit':'/admin/models/'.$a['id'].'/history')->withStatus(302);});
        $app->get('/admin/artifacts', static function ($request,$response) use ($twig,$artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);return$twig->render($response,'artifacts.twig',['artifacts'=>$artifacts->catalog()]);});
        $app->get('/admin/artifacts/new', static function ($request,$response) use ($twig) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);return$twig->render($response,'artifact-form.twig',['data'=>[]]);});
        $app->post('/admin/artifacts', static function (ServerRequestInterface $request,ResponseInterface $response) use ($artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$body=(array)$request->getParsedBody();$data=json_decode((string)($body['data_json']??'{}'),true);$id=$artifacts->create(trim((string)($body['slug']??'')),(string)($body['artifact_type']??'text'),trim((string)($body['title']??'')),trim((string)($body['description']??'')),is_array($data)?$data:[]);return$response->withHeader('Location','/admin/artifacts/'.$id.'/edit')->withStatus(302);});
        $app->get('/admin/artifacts/{id}/edit', static function ($request,$response,array $arguments) use ($twig,$artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$artifact=$artifacts->draft($arguments['id']);if($artifact===null)return$response->withStatus(404);return$twig->render($response,'artifact-form.twig',['artifact'=>$artifact,'data'=>$artifact['data']]);});
        $app->get('/admin/artifacts/{id}/usages', static function ($request,$response,array $arguments) use ($twig,$artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$catalog=array_values(array_filter($artifacts->catalog(),static fn(array $artifact):bool=>$artifact['id']===$arguments['id']));if($catalog===[])return$response->withStatus(404);return$twig->render($response,'artifact-usages.twig',['artifact'=>$catalog[0],'usages'=>$artifacts->usages($arguments['id'])]);});
        $app->get('/admin/artifacts/{id}/history/{language}', static function ($request,$response,array $a) use ($twig,$artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$history=$artifacts->history($a['id'],$a['language']);if($history===[])return$response->withStatus(404);$current=array_values(array_filter($history,static fn(array $revision):bool=>$revision['is_current']));return$twig->render($response,'artifact-history.twig',['artifact_id'=>$a['id'],'language'=>$a['language'],'history'=>$history,'current'=>$current[0]??null]);});
        $app->get('/admin/artifacts/{id}/compare/{language}', static function ($request,$response,array $a) use ($twig,$artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$q=$request->getQueryParams();$comparison=$artifacts->compareRevisions($a['id'],$a['language'],(string)($q['from']??''),(string)($q['to']??''));if($comparison===null)return$response->withStatus(404);return$twig->render($response,'artifact-comparison.twig',['artifact_id'=>$a['id'],'language'=>$a['language'],'comparison'=>$comparison]);});
        $app->post('/admin/artifacts/{id}/restore/{language}/{revision}', static function ($request,$response,array $a) use ($artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$id=$artifacts->restoreRevision($a['id'],$a['language'],$a['revision']);$path=$a['language']==='pt'?'/admin/artifacts/'.$a['id'].'/edit':'/admin/artifacts/'.$a['id'].'/'.$a['language'].'/edit';return$response->withHeader('Location',$id?$path:'/admin/artifacts/'.$a['id'].'/history/'.$a['language'])->withStatus(302);});
        $app->post('/admin/artifacts/{id}', static function (ServerRequestInterface $request,ResponseInterface $response,array $arguments) use ($artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$body=(array)$request->getParsedBody();$data=json_decode((string)($body['data_json']??'{}'),true);$artifacts->updateDraft($arguments['id'],trim((string)($body['title']??'')),trim((string)($body['description']??'')),is_array($data)?$data:[]);return$response->withHeader('Location','/admin/artifacts/'.$arguments['id'].'/edit')->withStatus(302);});
        $app->post('/admin/artifacts/{id}/publish', static function ($request,$response,array $arguments) use ($artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$artifacts->publish($arguments['id']);return$response->withHeader('Location','/admin/artifacts')->withStatus(302);});
        $app->post('/admin/artifacts/{id}/revisions', static function ($request,$response,array $arguments) use ($artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$artifacts->createRevision($arguments['id']);return$response->withHeader('Location','/admin/artifacts/'.$arguments['id'].'/edit')->withStatus(302);});
        $app->post('/admin/artifacts/{id}/translations/{language}', static function ($request,$response,array $arguments) use ($artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$artifacts->createTranslation($arguments['id'],$arguments['language']);return$response->withHeader('Location','/admin/artifacts/'.$arguments['id'].'/'.$arguments['language'].'/edit')->withStatus(302);});
        $app->post('/admin/artifacts/{id}/translations/{language}/refresh', static function ($request,$response,array $arguments) use ($artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$revision=$artifacts->refreshTranslation($arguments['id'],$arguments['language']);$path=$revision?'/admin/artifacts/'.$arguments['id'].'/'.$arguments['language'].'/edit':'/admin/translations';return$response->withHeader('Location',$path)->withStatus(302);});
        $app->get('/admin/artifacts/{id}/{language}/edit', static function ($request,$response,array $arguments) use ($twig,$artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$artifact=$artifacts->translationDraft($arguments['id'],$arguments['language']);if($artifact===null)return$response->withStatus(404);return$twig->render($response,'artifact-translation-form.twig',['artifact'=>$artifact,'data'=>$artifact['data']]);});
        $app->post('/admin/artifacts/{id}/{language}', static function (ServerRequestInterface $request,ResponseInterface $response,array $arguments) use ($artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$body=(array)$request->getParsedBody();$data=json_decode((string)($body['data_json']??'{}'),true);$artifacts->updateTranslationDraft($arguments['id'],$arguments['language'],trim((string)($body['title']??'')),trim((string)($body['description']??'')),is_array($data)?$data:[]);return$response->withHeader('Location','/admin/artifacts/'.$arguments['id'].'/'.$arguments['language'].'/edit')->withStatus(302);});
        $app->post('/admin/artifacts/{id}/{language}/publish', static function ($request,$response,array $arguments) use ($artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$artifacts->publishTranslation($arguments['id'],$arguments['language']);return$response->withHeader('Location','/admin/artifacts')->withStatus(302);});
        $app->post('/admin/artifacts/{id}/{language}/revisions', static function ($request,$response,array $arguments) use ($artifacts) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$artifacts->createTranslationRevision($arguments['id'],$arguments['language']);return$response->withHeader('Location','/admin/artifacts/'.$arguments['id'].'/'.$arguments['language'].'/edit')->withStatus(302);});
        $app->get('/admin/media', static function ($request,$response) use ($twig,$media) {if(!isset($_SESSION['user']))return$response->withHeader('Location','/login')->withStatus(302);return$twig->render($response,'media.twig',['media'=>$media->all()]);});
        $app->post('/admin/media', static function (ServerRequestInterface $request,ResponseInterface $response) use ($media) {if(!isset($_SESSION['user']))return$response->withHeader('Location','/login')->withStatus(302);$d=(array)$request->getParsedBody();$file=$request->getUploadedFiles()['file']??null;if($file===null||$file->getError()!==UPLOAD_ERR_OK)return$response->withHeader('Location','/admin/media')->withStatus(302);$path=tempnam(sys_get_temp_dir(),'usinadocs-media-');$file->moveTo($path);try{$media->store($path,$file->getClientFilename()??'image',(string)($d['title']??''),(string)($d['source_url']??''),(string)($d['license_note']??''));}finally{@unlink($path);}return$response->withHeader('Location','/admin/media')->withStatus(302);});
        $app->get('/admin/pages/new', static function ($request,$response) use ($twig,$media,$editorial,$artifacts) { if(!isset($_SESSION['user'])) return $response->withHeader('Location','/login')->withStatus(302); return $twig->render($response,'page-form.twig',['media'=>$media->all(),'models'=>$editorial->editorialModels(),'reusable_artifacts'=>$artifacts->publishedCatalog(),'blocks'=>[]]); });
        $app->post('/admin/pages', static function (ServerRequestInterface $request,ResponseInterface $response) use ($editorial) { if(!isset($_SESSION['user'])) return $response->withHeader('Location','/login')->withStatus(302); $d=(array)$request->getParsedBody(); $id=$editorial->create(trim((string)$d['title']),trim((string)$d['slug']),trim((string)$d['summary']),'','', '',(string)($d['content_type']??'reference'));$blocks=json_decode((string)($d['blocks_json']??'[]'),true);if(is_array($blocks))$editorial->replaceDraftBlocks($id,'pt',$blocks); return $response->withHeader('Location','/admin')->withStatus(302); });
        $app->post('/admin/pages/{id}/publish', static function ($request,$response,array $a) use ($editorial) { if(!isset($_SESSION['user'])) return $response->withHeader('Location','/login')->withStatus(302);$missing=$editorial->missingRequiredArtifacts($a['id']);if($missing!==[])return$response->withHeader('Location','/admin/pages/'.$a['id'].'/edit?missing='.rawurlencode(implode(', ',$missing)))->withStatus(302);$editorial->publish($a['id']); return $response->withHeader('Location','/admin')->withStatus(302); });
        $app->post('/admin/pages/{id}/revisions', static function ($request,$response,array $a) use ($editorial) { if(!isset($_SESSION['user'])) return $response->withHeader('Location','/login')->withStatus(302); $editorial->createRevision($a['id']); return $response->withHeader('Location','/admin/pages/'.$a['id'].'/edit')->withStatus(302); });
        $app->post('/admin/pages/{id}/revisions/{language}', static function ($request,$response,array $a) use ($editorial) {if(!isset($_SESSION['user']))return$response->withHeader('Location','/login')->withStatus(302);$editorial->createLocalizedRevision($a['id'],$a['language']);$path=$a['language']==='pt'?'/admin/pages/'.$a['id'].'/edit':'/admin/pages/'.$a['id'].'/'.$a['language'].'/edit';return$response->withHeader('Location',$path)->withStatus(302);});
        $app->post('/admin/pages/{id}/revisions/{language}/discard', static function ($request,$response,array $a) use ($editorial) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$editorial->discardDraft($a['id'],$a['language']);return$response->withHeader('Location','/admin')->withStatus(302);});
        $app->get('/admin/pages/{id}/history/{language}', static function ($request,$response,array $a) use ($editorial,$twig) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$history=$editorial->revisionHistory($a['id'],$a['language']);if($history===[])return$response->withStatus(404);$current=array_values(array_filter($history,static fn(array $revision):bool=>$revision['is_current']));return$twig->render($response,'page-history.twig',['page_id'=>$a['id'],'language'=>$a['language'],'history'=>$history,'current'=>$current[0]??null]);});
        $app->get('/admin/pages/{id}/compare/{language}', static function ($request,$response,array $a) use ($editorial,$twig) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$query=$request->getQueryParams();$comparison=$editorial->compareRevisions($a['id'],$a['language'],(string)($query['from']??''),(string)($query['to']??''));if($comparison===null)return$response->withStatus(404);return$twig->render($response,'page-comparison.twig',['page_id'=>$a['id'],'language'=>$a['language'],'comparison'=>$comparison]);});
        $app->post('/admin/pages/{id}/restore/{language}/{revision}', static function ($request,$response,array $a) use ($editorial) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$restored=$editorial->restoreRevision($a['id'],$a['language'],$a['revision']);if($restored===null)return$response->withHeader('Location','/admin/pages/'.$a['id'].'/history/'.$a['language'].'?restore=blocked')->withStatus(302);$path=$a['language']==='pt'?'/admin/pages/'.$a['id'].'/edit':'/admin/pages/'.$a['id'].'/'.$a['language'].'/edit';return$response->withHeader('Location',$path)->withStatus(302);});
        $app->get('/admin/pages/{id}/edit', static function ($request,$response,array $a) use ($editorial,$twig,$media,$artifacts) { if(!isset($_SESSION['user'])) return $response->withHeader('Location','/login')->withStatus(302); $page=$editorial->draft($a['id']); if($page===null)return $response->withStatus(404); return $twig->render($response,'page-form.twig',['page'=>$page,'media'=>$media->all(),'models'=>$editorial->editorialModels(),'reusable_artifacts'=>$artifacts->publishedCatalog(),'blocks'=>$editorial->blocksForDraft($a['id'],'pt'),'missing'=>(string)($request->getQueryParams()['missing']??'')]); });
        $app->post('/admin/pages/{id}', static function (ServerRequestInterface $request,ResponseInterface $response,array $a) use ($editorial) { if(!isset($_SESSION['user'])) return $response->withHeader('Location','/login')->withStatus(302);$d=(array)$request->getParsedBody();$editorial->setContentType($a['id'],(string)($d['content_type']??'reference'));$editorial->updateDraft($a['id'],trim((string)$d['title']),trim((string)$d['summary']),'','');$blocks=json_decode((string)($d['blocks_json']??'[]'),true);if(is_array($blocks))$editorial->replaceDraftBlocks($a['id'],'pt',$blocks);return $response->withHeader('Location','/admin')->withStatus(302); });
        $app->post('/admin/pages/{id}/translations/{language}', static function (ServerRequestInterface $request,ResponseInterface $response,array $a) use ($editorial) { if(!isset($_SESSION['user']))return$response->withHeader('Location','/login')->withStatus(302);$d=(array)$request->getParsedBody();$editorial->createTranslation($a['id'],$a['language'],trim((string)$d['slug']));return$response->withHeader('Location','/admin/pages/'.$a['id'].'/'.$a['language'].'/edit')->withStatus(302);});
        $app->post('/admin/pages/{id}/translations/{language}/refresh', static function ($request,$response,array $a) use ($editorial) {if(!isset($_SESSION['user'])||$_SESSION['user']['role']!=='administrator')return$response->withHeader('Location','/login')->withStatus(302);$revision=$editorial->refreshTranslation($a['id'],$a['language']);if($revision===null)return$response->withHeader('Location','/admin/translations')->withStatus(302);return$response->withHeader('Location','/admin/pages/'.$a['id'].'/'.$a['language'].'/edit')->withStatus(302);});
        $app->get('/admin/pages/{id}/translations/{language}/new', static function ($request,$response,array $a) use ($twig) {if(!isset($_SESSION['user']))return$response->withHeader('Location','/login')->withStatus(302);if(!in_array($a['language'],['en','es'],true))return$response->withStatus(404);return$twig->render($response,'translation-form.twig',['page_id'=>$a['id'],'language'=>$a['language']]);});
        $app->get('/admin/pages/{id}/{language}/edit', static function ($request,$response,array $a) use ($editorial,$twig,$media,$artifacts) { if(!isset($_SESSION['user']))return$response->withHeader('Location','/login')->withStatus(302);$page=$editorial->localizedDraft($a['id'],$a['language']);if($page===null)return$response->withStatus(404);return$twig->render($response,'page-form.twig',['page'=>$page,'media'=>$media->all(),'models'=>$editorial->editorialModels(),'reusable_artifacts'=>$artifacts->publishedCatalog($a['language']),'blocks'=>$editorial->blocksForDraft($a['id'],$a['language']),'missing'=>(string)($request->getQueryParams()['missing']??'')]);});
        $app->post('/admin/pages/{id}/{language}', static function (ServerRequestInterface $request,ResponseInterface $response,array $a) use ($editorial) { if(!isset($_SESSION['user']))return$response->withHeader('Location','/login')->withStatus(302);$d=(array)$request->getParsedBody();$editorial->setContentType($a['id'],(string)($d['content_type']??'reference'));$editorial->updateLocalizedDraft($a['id'],$a['language'],trim((string)$d['title']),trim((string)$d['summary']),'','');$blocks=json_decode((string)($d['blocks_json']??'[]'),true);if(is_array($blocks))$editorial->replaceDraftBlocks($a['id'],$a['language'],$blocks);return$response->withHeader('Location','/admin/pages/'.$a['id'].'/'.$a['language'].'/edit')->withStatus(302);});
        $app->post('/admin/pages/{id}/{language}/publish', static function ($request,$response,array $a) use ($editorial) {if(!isset($_SESSION['user']))return$response->withHeader('Location','/login')->withStatus(302);$missing=$editorial->missingRequiredArtifacts($a['id'],$a['language']);if($missing!==[])return$response->withHeader('Location','/admin/pages/'.$a['id'].'/'.$a['language'].'/edit?missing='.rawurlencode(implode(', ',$missing)))->withStatus(302);$editorial->publishLocalized($a['id'],$a['language']);return$response->withHeader('Location','/admin')->withStatus(302);});

        return $app;
    }
}
