<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Usina Docs: plataforma aberta para documentação e aprendizado.">
    <title>{{ $title ?? 'Usina Docs' }}</title>
    <style>
        :root { color-scheme:light; --ink:#10243b; --ink-soft:#40556d; --paper:#fff; --canvas:#f4f7fa; --line:#d9e2eb; --brand:#0069a9; --brand-deep:#004c7a; --accent:#f47d20; --accent-soft:#fff1e5; --code:#11283d; --success:#146c43; --radius:16px; }
        * { box-sizing:border-box; } body { margin:0; background:var(--canvas); color:var(--ink); font:16px/1.6 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif; } a { color:var(--brand-deep); } .shell { width:min(1160px,calc(100% - 40px)); margin:auto; }
        .site-header { background:rgba(255,255,255,.94); border-bottom:1px solid var(--line); position:sticky; top:0; z-index:10; backdrop-filter:blur(12px); } .site-nav { min-height:76px; display:flex; justify-content:space-between; align-items:center; gap:24px; }
        .brand { align-items:center; color:var(--ink); display:inline-flex; font-size:1.08rem; font-weight:850; gap:10px; letter-spacing:-.035em; text-decoration:none; } .brand-mark { background:linear-gradient(145deg,var(--brand),#138ac8); border-radius:9px 9px 9px 3px; display:grid; height:30px; place-items:center; width:30px; } .brand-mark::after { border:2px solid #fff; border-top:0; content:""; height:9px; width:11px; } .brand em { color:var(--brand); font-style:normal; }
        .nav-links { align-items:center; display:flex; flex-wrap:wrap; gap:18px; } .nav-links a { color:var(--ink-soft); font-size:.92rem; font-weight:700; text-decoration:none; } .nav-links a:hover { color:var(--brand); }
        main.shell { min-height:calc(100vh - 150px); padding:68px 0 80px; } .eyebrow { color:var(--brand); font-size:.75rem; font-weight:850; letter-spacing:.12em; margin:0; text-transform:uppercase; } h1,h2,h3,p { margin-top:0; } h1 { font-size:clamp(2.3rem,6vw,4.6rem); letter-spacing:-.062em; line-height:.98; margin:12px 0 20px; max-width:900px; } h2 { font-size:1.2rem; letter-spacing:-.025em; line-height:1.2; margin-bottom:10px; } .lead { color:var(--ink-soft); font-size:1.16rem; max-width:720px; } .meta { color:var(--ink-soft); font-size:.88rem; }
        .actions { align-items:center; display:flex; flex-wrap:wrap; gap:12px; margin-top:30px; } .button { appearance:none; background:var(--brand); border:1px solid var(--brand); border-radius:10px; color:#fff; cursor:pointer; display:inline-flex; font:inherit; font-weight:800; justify-content:center; padding:10px 15px; text-decoration:none; transition:.16s ease; } .button:hover { background:var(--brand-deep); border-color:var(--brand-deep); transform:translateY(-1px); } .button.alt { background:transparent; color:var(--brand-deep); } .button.alt:hover { background:#e8f3fa; }
        .grid { display:grid; gap:18px; grid-template-columns:repeat(3,1fr); margin-top:56px; } .card { background:var(--paper); border:1px solid var(--line); border-radius:var(--radius); box-shadow:0 6px 22px rgba(16,36,59,.04); padding:24px; } .card p:last-child { margin-bottom:0; } .card p { color:var(--ink-soft); }
        .article { max-width:820px; } .article-header { border-bottom:1px solid var(--line); margin-bottom:28px; padding-bottom:28px; } .article-header h1 { font-size:clamp(2.2rem,5vw,3.8rem); } .block { background:var(--paper); border:1px solid var(--line); border-radius:var(--radius); margin:18px 0; overflow:hidden; padding:26px; } .block > .eyebrow { margin-bottom:12px; } .block p:last-child { margin-bottom:0; } pre { background:var(--code); border-radius:11px; color:#e8f3fb; margin:0; overflow:auto; padding:18px; } code { font:14px/1.6 ui-monospace,SFMono-Regular,Consolas,monospace; }
        .section-heading { align-items:end; display:flex; gap:24px; justify-content:space-between; margin-bottom:26px; } .section-heading h1 { font-size:clamp(2.1rem,5vw,3.5rem); margin-bottom:8px; } .panel { background:var(--paper); border:1px solid var(--line); border-radius:var(--radius); padding:28px; } .page-list { display:grid; gap:14px; } .page-row { align-items:center; background:var(--paper); border:1px solid var(--line); border-radius:13px; display:flex; gap:20px; justify-content:space-between; padding:18px 20px; } .page-row h2 { margin:0; } .locale-list { color:var(--ink-soft); display:flex; flex-wrap:wrap; font-size:.9rem; gap:10px; margin-top:8px; } .status { border-radius:999px; font-size:.72rem; font-weight:800; padding:3px 8px; } .status.live { background:#e5f7ec; color:var(--success); } .status.pending { background:var(--accent-soft); color:#9c4600; }
        label { color:var(--ink); font-size:.9rem; font-weight:800; } input,select,textarea { background:#fff; border:1px solid #bdcad7; border-radius:9px; color:var(--ink); font:inherit; margin-top:5px; max-width:100%; padding:9px 11px; width:100%; } textarea { resize:vertical; } input:focus,select:focus,textarea:focus { border-color:var(--brand); box-shadow:0 0 0 3px rgba(0,105,169,.13); outline:0; } fieldset { border:0; padding:0; } legend { font-weight:850; } .notice { background:#e8f3fa; border:1px solid #b8d9ec; border-radius:11px; color:#124969; padding:12px 14px; }
        .site-footer { border-top:1px solid var(--line); color:var(--ink-soft); font-size:.86rem; padding:26px 0; } .footer-inner { align-items:center; display:flex; gap:12px; justify-content:space-between; } .footer-inner span { color:var(--accent); font-weight:800; }
        @media (max-width:720px) { .shell { width:min(100% - 28px,1160px); } .site-nav { min-height:66px; } .nav-links { gap:12px; } main.shell { padding:42px 0 56px; } .grid { grid-template-columns:1fr; margin-top:36px; } .section-heading,.page-row,.footer-inner { align-items:flex-start; flex-direction:column; } .card,.panel,.block { padding:20px; } }
    </style>
</head>
<body>
<header class="site-header"><nav class="site-nav shell"><a class="brand" href="{{ url('/') }}"><span class="brand-mark" aria-hidden="true"></span><span>Usina <em>Docs</em></span></a><div class="nav-links"><a href="{{ route('pages.show', ['locale' => 'pt', 'slug' => 'bem-vindo']) }}">Demonstração</a>@auth <a href="{{ route('admin.dashboard') }}">Administração</a>@else <a href="{{ route('login') }}">Entrar</a>@endauth</div></nav></header>
<main class="shell">{{ $slot }}</main>
<footer class="site-footer"><div class="shell footer-inner"><span>Usina Docs</span><div>Pré-alfa · Código sob MPL-2.0</div></div></footer>
</body>
</html>
