<?php
declare(strict_types=1);
namespace UsinaDocs\Core\Content;
use PDO;
final class EditorialService {
 public function __construct(private readonly PDO $db) {}
 public function create(string $title,string $slug,string $summary,string $body,string $code,string $imageId='',string $contentType='reference'): string {
  $id='page-'.bin2hex(random_bytes(8)); $revision='revision-'.bin2hex(random_bytes(8)); $now=gmdate('c');
  $this->db->beginTransaction(); try {
   $this->db->prepare("INSERT INTO pages (id,site_id,created_at,updated_at) VALUES (:id,'site-usinadocs',:now,:now)")->execute(['id'=>$id,'now'=>$now]);
   $this->setContentType($id,$contentType,$now);
   $this->db->prepare("INSERT INTO page_revisions (id,page_id,language_code,number,status,title,summary,created_at) VALUES (:id,:page,'pt',1,'draft',:title,:summary,:now)")->execute(['id'=>$revision,'page'=>$id,'title'=>$title,'summary'=>$summary,'now'=>$now]);
   $this->db->prepare("INSERT INTO page_localizations (page_id,language_code,slug) VALUES (:page,'pt',:slug)")->execute(['page'=>$id,'slug'=>$slug]);
   $s=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');
   $s->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$revision,'type'=>'text','position'=>1,'data'=>json_encode(['body'=>$body],JSON_UNESCAPED_UNICODE)]);
   if ($code !== '') $s->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$revision,'type'=>'code','position'=>2,'data'=>json_encode(['language'=>'advpl','code'=>$code],JSON_UNESCAPED_UNICODE)]);
   if ($imageId !== '') $s->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$revision,'type'=>'image','position'=>3,'data'=>json_encode(['id'=>$imageId],JSON_UNESCAPED_UNICODE)]);
   $this->db->commit(); return $id;
  } catch (\Throwable $e) { $this->db->rollBack(); throw $e; }
 }
 public function publish(string $id): void { $r=$this->db->prepare("SELECT id FROM page_revisions WHERE page_id=:page AND status='draft' ORDER BY number DESC LIMIT 1"); $r->execute(['page'=>$id]); $revision=$r->fetchColumn(); if(!$revision) return; $now=gmdate('c'); $this->db->prepare("UPDATE page_revisions SET status='published',published_at=:now WHERE id=:id")->execute(['now'=>$now,'id'=>$revision]); $this->db->prepare("UPDATE page_localizations SET published_revision_id=:revision WHERE page_id=:page AND language_code='pt'")->execute(['revision'=>$revision,'page'=>$id]); }
 public function drafts(): array { return $this->db->query("SELECT p.id,r.title,pl.slug,r.status FROM pages p JOIN page_revisions r ON r.page_id=p.id JOIN page_localizations pl ON pl.page_id=p.id AND pl.language_code='pt' WHERE r.status='draft' ORDER BY r.created_at DESC")->fetchAll(PDO::FETCH_ASSOC); }
 public function published(): array { return $this->db->query("SELECT p.id,r.title,pl.slug,r.number FROM pages p JOIN page_localizations pl ON pl.page_id=p.id AND pl.language_code='pt' JOIN page_revisions r ON r.id=pl.published_revision_id ORDER BY r.published_at DESC")->fetchAll(PDO::FETCH_ASSOC); }
 public function createRevision(string $pageId): ?string { $published=$this->db->prepare("SELECT r.* FROM page_localizations pl JOIN page_revisions r ON r.id=pl.published_revision_id WHERE pl.page_id=:page AND pl.language_code='pt'"); $published->execute(['page'=>$pageId]); $source=$published->fetch(PDO::FETCH_ASSOC); if($source===false) return null; $existing=$this->db->prepare("SELECT id FROM page_revisions WHERE page_id=:page AND status='draft'"); $existing->execute(['page'=>$pageId]); if($id=$existing->fetchColumn()) return $id; $new='revision-'.bin2hex(random_bytes(8)); $now=gmdate('c'); $number=(int)$this->db->query("SELECT COALESCE(MAX(number),0)+1 FROM page_revisions WHERE page_id=".$this->db->quote($pageId))->fetchColumn(); $this->db->beginTransaction(); try { $this->db->prepare("INSERT INTO page_revisions (id,page_id,language_code,number,status,title,summary,created_at) VALUES (:id,:page,'pt',:number,'draft',:title,:summary,:created)")->execute(['id'=>$new,'page'=>$pageId,'number'=>$number,'title'=>$source['title'],'summary'=>$source['summary'],'created'=>$now]); $blocks=$this->db->prepare('SELECT type,position,data FROM blocks WHERE page_revision_id=:revision ORDER BY position'); $blocks->execute(['revision'=>$source['id']]); $copy=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)'); foreach($blocks->fetchAll(PDO::FETCH_ASSOC) as $block) $copy->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$new,'type'=>$block['type'],'position'=>$block['position'],'data'=>$block['data']]); $this->db->commit(); return $new; } catch(\Throwable $e) { $this->db->rollBack(); throw $e; } }
 public function setContentType(string $pageId,string $contentType,?string $now=null):void{if(!in_array($contentType,['reference','article','lesson','class','entry_point'],true))$contentType='reference';$this->db->prepare("INSERT INTO page_metadata (page_id,content_type,updated_at) VALUES (:page,:type,:updated) ON CONFLICT(page_id) DO UPDATE SET content_type=excluded.content_type,updated_at=excluded.updated_at")->execute(['page'=>$pageId,'type'=>$contentType,'updated'=>$now??gmdate('c')]);}
 public function draft(string $pageId): ?array { $statement=$this->db->prepare("SELECT p.id AS page_id,pl.slug,r.id AS revision_id,r.title,r.summary,COALESCE(m.content_type,'reference') AS content_type FROM pages p JOIN page_localizations pl ON pl.page_id=p.id AND pl.language_code='pt' JOIN page_revisions r ON r.page_id=p.id LEFT JOIN page_metadata m ON m.page_id=p.id WHERE p.id=:page AND r.status='draft' ORDER BY r.number DESC LIMIT 1"); $statement->execute(['page'=>$pageId]); $page=$statement->fetch(PDO::FETCH_ASSOC); if($page===false)return null; $blocks=$this->db->prepare('SELECT type,data FROM blocks WHERE page_revision_id=:revision ORDER BY position'); $blocks->execute(['revision'=>$page['revision_id']]); $page['body']='';$page['code']='';foreach($blocks->fetchAll(PDO::FETCH_ASSOC) as $block){$data=json_decode($block['data'],true);if($block['type']==='text')$page['body']=$data['body']??'';if($block['type']==='code')$page['code']=$data['code']??'';}return $page; }
 public function updateDraft(string $pageId,string $title,string $summary,string $body,string $code): void { $draft=$this->draft($pageId);if($draft===null)return; $this->db->beginTransaction();try{$this->db->prepare('UPDATE page_revisions SET title=:title,summary=:summary WHERE id=:id')->execute(['title'=>$title,'summary'=>$summary,'id'=>$draft['revision_id']]);$this->db->prepare('DELETE FROM blocks WHERE page_revision_id=:revision')->execute(['revision'=>$draft['revision_id']]);$add=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$draft['revision_id'],'type'=>'text','position'=>1,'data'=>json_encode(['body'=>$body],JSON_UNESCAPED_UNICODE)]);if($code!=='')$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$draft['revision_id'],'type'=>'code','position'=>2,'data'=>json_encode(['language'=>'advpl','code'=>$code],JSON_UNESCAPED_UNICODE)]);$this->db->commit();}catch(\Throwable $e){$this->db->rollBack();throw $e;} }
 public function createTranslation(string $pageId,string $language,string $slug): ?string { if(!in_array($language,['en','es'],true))return null;$source=$this->db->prepare("SELECT r.* FROM page_localizations pl JOIN page_revisions r ON r.id=pl.published_revision_id WHERE pl.page_id=:page AND pl.language_code='pt'");$source->execute(['page'=>$pageId]);$base=$source->fetch(PDO::FETCH_ASSOC);if($base===false)return null;$exists=$this->db->prepare('SELECT 1 FROM page_localizations WHERE page_id=:page AND language_code=:language');$exists->execute(['page'=>$pageId,'language'=>$language]);if($exists->fetchColumn())return null;$revision='revision-'.bin2hex(random_bytes(8));$number=(int)$this->db->query("SELECT COALESCE(MAX(number),0)+1 FROM page_revisions WHERE page_id=".$this->db->quote($pageId))->fetchColumn();$now=gmdate('c');$this->db->beginTransaction();try{$this->db->prepare('INSERT INTO page_localizations (page_id,language_code,slug) VALUES (:page,:language,:slug)')->execute(['page'=>$pageId,'language'=>$language,'slug'=>$slug]);$this->db->prepare("INSERT INTO page_revisions (id,page_id,language_code,number,status,title,summary,created_at) VALUES (:id,:page,:language,:number,'draft',:title,:summary,:created)")->execute(['id'=>$revision,'page'=>$pageId,'language'=>$language,'number'=>$number,'title'=>$base['title'],'summary'=>$base['summary'],'created'=>$now]);$blocks=$this->db->prepare('SELECT type,position,data FROM blocks WHERE page_revision_id=:revision');$blocks->execute(['revision'=>$base['id']]);$add=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');foreach($blocks->fetchAll(PDO::FETCH_ASSOC)as$block)$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$revision,'type'=>$block['type'],'position'=>$block['position'],'data'=>$block['data']]);$this->db->commit();return $revision;}catch(\Throwable$e){$this->db->rollBack();throw$e;} }
 public function localizedDraft(string $pageId,string $language): ?array {$s=$this->db->prepare("SELECT p.id AS page_id,pl.slug,r.id AS revision_id,r.title,r.summary,COALESCE(m.content_type,'reference') AS content_type FROM pages p JOIN page_localizations pl ON pl.page_id=p.id AND pl.language_code=:language JOIN page_revisions r ON r.page_id=p.id AND r.language_code=:language LEFT JOIN page_metadata m ON m.page_id=p.id WHERE p.id=:page AND r.status='draft' ORDER BY r.number DESC LIMIT 1");$s->execute(['page'=>$pageId,'language'=>$language]);$page=$s->fetch(PDO::FETCH_ASSOC);if($page===false)return null;$page['language']=$language;$b=$this->db->prepare('SELECT type,data FROM blocks WHERE page_revision_id=:revision ORDER BY position');$b->execute(['revision'=>$page['revision_id']]);$page['body']='';$page['code']='';foreach($b->fetchAll(PDO::FETCH_ASSOC)as$block){$data=json_decode($block['data'],true);if($block['type']==='text')$page['body']=$data['body']??'';if($block['type']==='code')$page['code']=$data['code']??'';}return$page;}
 public function updateLocalizedDraft(string $pageId,string $language,string $title,string $summary,string $body,string $code):void{$draft=$this->localizedDraft($pageId,$language);if($draft===null)return;$this->db->beginTransaction();try{$this->db->prepare('UPDATE page_revisions SET title=:title,summary=:summary WHERE id=:id')->execute(['title'=>$title,'summary'=>$summary,'id'=>$draft['revision_id']]);$this->db->prepare('DELETE FROM blocks WHERE page_revision_id=:revision')->execute(['revision'=>$draft['revision_id']]);$add=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$draft['revision_id'],'type'=>'text','position'=>1,'data'=>json_encode(['body'=>$body],JSON_UNESCAPED_UNICODE)]);if($code!=='')$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$draft['revision_id'],'type'=>'code','position'=>2,'data'=>json_encode(['language'=>'advpl','code'=>$code],JSON_UNESCAPED_UNICODE)]);$this->db->commit();}catch(\Throwable$e){$this->db->rollBack();throw$e;}}
 public function publishLocalized(string $pageId,string $language):void{$s=$this->db->prepare("SELECT id FROM page_revisions WHERE page_id=:page AND language_code=:language AND status='draft' ORDER BY number DESC LIMIT 1");$s->execute(['page'=>$pageId,'language'=>$language]);$revision=$s->fetchColumn();if(!$revision)return;$this->db->prepare("UPDATE page_revisions SET status='published',published_at=:now WHERE id=:id")->execute(['now'=>gmdate('c'),'id'=>$revision]);$this->db->prepare('UPDATE page_localizations SET published_revision_id=:revision WHERE page_id=:page AND language_code=:language')->execute(['revision'=>$revision,'page'=>$pageId,'language'=>$language]);}
 public function translationReview(string $search=''):array{
  $statement=$this->db->prepare("SELECT p.id,pt.title,pt.number AS pt_number,en.slug AS en_slug,enr.number AS en_number,endraft.id AS en_draft,es.slug AS es_slug,esr.number AS es_number,esdraft.id AS es_draft FROM pages p JOIN page_localizations ptloc ON ptloc.page_id=p.id AND ptloc.language_code='pt' JOIN page_revisions pt ON pt.id=ptloc.published_revision_id LEFT JOIN page_localizations en ON en.page_id=p.id AND en.language_code='en' LEFT JOIN page_revisions enr ON enr.id=en.published_revision_id LEFT JOIN page_revisions endraft ON endraft.page_id=p.id AND endraft.language_code='en' AND endraft.status='draft' LEFT JOIN page_localizations es ON es.page_id=p.id AND es.language_code='es' LEFT JOIN page_revisions esr ON esr.id=es.published_revision_id LEFT JOIN page_revisions esdraft ON esdraft.page_id=p.id AND esdraft.language_code='es' AND esdraft.status='draft' WHERE pt.title LIKE :search ORDER BY pt.title");
  $statement->execute(['search'=>'%'.$search.'%']);
  return array_map(static function(array $page):array{
   foreach(['en','es'] as $language){$published=$page[$language.'_number'];$draft=$page[$language.'_draft'];$page[$language.'_status']=$draft!==null?'draft':($published===null?'absent':((int)$published<(int)$page['pt_number']?'outdated':'published'));}
   return $page;
  },$statement->fetchAll(PDO::FETCH_ASSOC));
 }
 public function refreshTranslation(string $pageId,string $language):?string{
  if(!in_array($language,['en','es'],true))return null;
  $existing=$this->db->prepare("SELECT id FROM page_revisions WHERE page_id=:page AND language_code=:language AND status='draft'");$existing->execute(['page'=>$pageId,'language'=>$language]);if($draft=$existing->fetchColumn())return $draft;
  $base=$this->db->prepare("SELECT r.* FROM page_localizations pl JOIN page_revisions r ON r.id=pl.published_revision_id WHERE pl.page_id=:page AND pl.language_code='pt'");$base->execute(['page'=>$pageId]);$source=$base->fetch(PDO::FETCH_ASSOC);if($source===false)return null;
  $localized=$this->db->prepare('SELECT 1 FROM page_localizations WHERE page_id=:page AND language_code=:language');$localized->execute(['page'=>$pageId,'language'=>$language]);if(!$localized->fetchColumn())return null;
  $revision='revision-'.bin2hex(random_bytes(8));$number=(int)$this->db->query("SELECT COALESCE(MAX(number),0)+1 FROM page_revisions WHERE page_id=".$this->db->quote($pageId))->fetchColumn();
  $this->db->beginTransaction();try{$this->db->prepare("INSERT INTO page_revisions (id,page_id,language_code,number,status,title,summary,created_at) VALUES (:id,:page,:language,:number,'draft',:title,:summary,:created)")->execute(['id'=>$revision,'page'=>$pageId,'language'=>$language,'number'=>$number,'title'=>$source['title'],'summary'=>$source['summary'],'created'=>gmdate('c')]);$blocks=$this->db->prepare('SELECT type,position,data FROM blocks WHERE page_revision_id=:revision ORDER BY position');$blocks->execute(['revision'=>$source['id']]);$copy=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');foreach($blocks->fetchAll(PDO::FETCH_ASSOC)as$block)$copy->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$revision,'type'=>$block['type'],'position'=>$block['position'],'data'=>$block['data']]);$this->db->commit();return$revision;}catch(\Throwable$exception){$this->db->rollBack();throw$exception;}
 }
 public function catalog(string $search=''):array{$s=$this->db->prepare("SELECT p.id,COALESCE(pt.title,ptr.title,'(sem título)') AS title,ptloc.slug AS pt_slug,en.slug AS en_slug,es.slug AS es_slug,CASE WHEN ptloc.published_revision_id IS NOT NULL THEN 'published' WHEN ptr.id IS NOT NULL THEN 'draft' ELSE 'missing' END AS pt_status,CASE WHEN en.published_revision_id IS NOT NULL THEN 'published' WHEN enr.id IS NOT NULL THEN 'draft' WHEN en.page_id IS NOT NULL THEN 'missing' ELSE 'absent' END AS en_status,CASE WHEN es.published_revision_id IS NOT NULL THEN 'published' WHEN esr.id IS NOT NULL THEN 'draft' WHEN es.page_id IS NOT NULL THEN 'missing' ELSE 'absent' END AS es_status FROM pages p LEFT JOIN page_localizations ptloc ON ptloc.page_id=p.id AND ptloc.language_code='pt' LEFT JOIN page_revisions pt ON pt.id=ptloc.published_revision_id LEFT JOIN page_revisions ptr ON ptr.page_id=p.id AND ptr.language_code='pt' AND ptr.status='draft' LEFT JOIN page_localizations en ON en.page_id=p.id AND en.language_code='en' LEFT JOIN page_revisions enr ON enr.page_id=p.id AND enr.language_code='en' AND enr.status='draft' LEFT JOIN page_localizations es ON es.page_id=p.id AND es.language_code='es' LEFT JOIN page_revisions esr ON esr.page_id=p.id AND esr.language_code='es' AND esr.status='draft' WHERE COALESCE(pt.title,ptr.title) LIKE :search ORDER BY COALESCE(pt.title,ptr.title)");$s->execute(['search'=>'%'.$search.'%']);return$s->fetchAll(PDO::FETCH_ASSOC);}
 public function replaceDraftBlocks(string $pageId,string $language,array $blocks):void{$s=$this->db->prepare("SELECT id FROM page_revisions WHERE page_id=:page AND language_code=:language AND status='draft' ORDER BY number DESC LIMIT 1");$s->execute(['page'=>$pageId,'language'=>$language]);$revision=$s->fetchColumn();if(!$revision)return;$allowed=['heading','text','code','image','reference','citation','diagram','notice','table'];$this->db->beginTransaction();try{$this->db->prepare('DELETE FROM blocks WHERE page_revision_id=:revision')->execute(['revision'=>$revision]);$add=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');foreach(array_values($blocks)as$position=>$block){if(!is_array($block)||!in_array($block['type']??'', $allowed,true)||!is_array($block['data']??null))continue;$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$revision,'type'=>$block['type'],'position'=>$position+1,'data'=>json_encode($block['data'],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)]);}$this->db->commit();}catch(\Throwable$e){$this->db->rollBack();throw$e;}}
 public function blocksForDraft(string $pageId,string $language):array{$s=$this->db->prepare("SELECT b.type,b.data FROM page_revisions r JOIN blocks b ON b.page_revision_id=r.id WHERE r.page_id=:page AND r.language_code=:language AND r.status='draft' ORDER BY r.number DESC,b.position");$s->execute(['page'=>$pageId,'language'=>$language]);return array_map(static fn(array $b):array=>['type'=>$b['type'],'data'=>json_decode($b['data'],true,512,JSON_THROW_ON_ERROR)],$s->fetchAll(PDO::FETCH_ASSOC));}
 public function createLocalizedRevision(string $pageId,string $language):?string{if(!in_array($language,['pt','en','es'],true))return null;$published=$this->db->prepare("SELECT r.* FROM page_localizations pl JOIN page_revisions r ON r.id=pl.published_revision_id WHERE pl.page_id=:page AND pl.language_code=:language");$published->execute(['page'=>$pageId,'language'=>$language]);$source=$published->fetch(PDO::FETCH_ASSOC);if($source===false)return null;$existing=$this->db->prepare("SELECT id FROM page_revisions WHERE page_id=:page AND language_code=:language AND status='draft'");$existing->execute(['page'=>$pageId,'language'=>$language]);if($id=$existing->fetchColumn())return$id;$new='revision-'.bin2hex(random_bytes(8));$number=(int)$this->db->query("SELECT COALESCE(MAX(number),0)+1 FROM page_revisions WHERE page_id=".$this->db->quote($pageId))->fetchColumn();$this->db->beginTransaction();try{$this->db->prepare("INSERT INTO page_revisions (id,page_id,language_code,number,status,title,summary,created_at) VALUES (:id,:page,:language,:number,'draft',:title,:summary,:created)")->execute(['id'=>$new,'page'=>$pageId,'language'=>$language,'number'=>$number,'title'=>$source['title'],'summary'=>$source['summary'],'created'=>gmdate('c')]);$blocks=$this->db->prepare('SELECT type,position,data FROM blocks WHERE page_revision_id=:revision ORDER BY position');$blocks->execute(['revision'=>$source['id']]);$add=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');foreach($blocks->fetchAll(PDO::FETCH_ASSOC)as$block)$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$new,'type'=>$block['type'],'position'=>$block['position'],'data'=>$block['data']]);$this->db->commit();return$new;}catch(\Throwable$e){$this->db->rollBack();throw$e;}}
 public function editorialModels():array{$rows=$this->db->query('SELECT m.id,m.content_type,m.label,m.description,a.artifact_type,a.label AS artifact_label,a.is_required,a.position FROM editorial_models m LEFT JOIN editorial_model_artifacts a ON a.model_id=m.id ORDER BY m.label,a.position')->fetchAll(PDO::FETCH_ASSOC);$models=[];foreach($rows as $row){$id=$row['id'];if(!isset($models[$id]))$models[$id]=['id'=>$id,'content_type'=>$row['content_type'],'label'=>$row['label'],'description'=>$row['description'],'artifacts'=>[]];if($row['artifact_type']!==null)$models[$id]['artifacts'][]=['type'=>$row['artifact_type'],'label'=>$row['artifact_label'],'required'=>(bool)$row['is_required']];}return array_values($models);}
 public function discardDraft(string $pageId,string $language):void{$draft=$this->db->prepare("SELECT id FROM page_revisions WHERE page_id=:page AND language_code=:language AND status='draft' ORDER BY number DESC LIMIT 1");$draft->execute(['page'=>$pageId,'language'=>$language]);$revision=$draft->fetchColumn();if(!$revision)return;$this->db->beginTransaction();try{$this->db->prepare('DELETE FROM blocks WHERE page_revision_id=:revision')->execute(['revision'=>$revision]);$this->db->prepare('DELETE FROM page_revisions WHERE id=:revision')->execute(['revision'=>$revision]);$remaining=$this->db->prepare('SELECT COUNT(*) FROM page_revisions WHERE page_id=:page');$remaining->execute(['page'=>$pageId]);if((int)$remaining->fetchColumn()===0){$this->db->prepare('DELETE FROM page_metadata WHERE page_id=:page')->execute(['page'=>$pageId]);$this->db->prepare('DELETE FROM page_localizations WHERE page_id=:page')->execute(['page'=>$pageId]);$this->db->prepare('DELETE FROM pages WHERE id=:page')->execute(['page'=>$pageId]);}$this->db->commit();}catch(\Throwable$exception){$this->db->rollBack();throw$exception;}}
}
