<?php
declare(strict_types=1);
namespace UsinaDocs\Core\Content;
use PDO;
final class EditorialService {
 public function __construct(private readonly PDO $db) {}
 public function create(string $title,string $slug,string $summary,string $body,string $code): string {
  $id='page-'.bin2hex(random_bytes(8)); $revision='revision-'.bin2hex(random_bytes(8)); $now=gmdate('c');
  $this->db->beginTransaction(); try {
   $this->db->prepare("INSERT INTO pages (id,site_id,created_at,updated_at) VALUES (:id,'site-usinadocs',:now,:now)")->execute(['id'=>$id,'now'=>$now]);
   $this->db->prepare("INSERT INTO page_revisions (id,page_id,language_code,number,status,title,summary,created_at) VALUES (:id,:page,'pt',1,'draft',:title,:summary,:now)")->execute(['id'=>$revision,'page'=>$id,'title'=>$title,'summary'=>$summary,'now'=>$now]);
   $this->db->prepare("INSERT INTO page_localizations (page_id,language_code,slug) VALUES (:page,'pt',:slug)")->execute(['page'=>$id,'slug'=>$slug]);
   $s=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');
   $s->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$revision,'type'=>'text','position'=>1,'data'=>json_encode(['body'=>$body],JSON_UNESCAPED_UNICODE)]);
   if ($code !== '') $s->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$revision,'type'=>'code','position'=>2,'data'=>json_encode(['language'=>'advpl','code'=>$code],JSON_UNESCAPED_UNICODE)]);
   $this->db->commit(); return $id;
  } catch (\Throwable $e) { $this->db->rollBack(); throw $e; }
 }
 public function publish(string $id): void { $r=$this->db->prepare("SELECT id FROM page_revisions WHERE page_id=:page AND status='draft' ORDER BY number DESC LIMIT 1"); $r->execute(['page'=>$id]); $revision=$r->fetchColumn(); if(!$revision) return; $now=gmdate('c'); $this->db->prepare("UPDATE page_revisions SET status='published',published_at=:now WHERE id=:id")->execute(['now'=>$now,'id'=>$revision]); $this->db->prepare("UPDATE page_localizations SET published_revision_id=:revision WHERE page_id=:page AND language_code='pt'")->execute(['revision'=>$revision,'page'=>$id]); }
 public function drafts(): array { return $this->db->query("SELECT p.id,r.title,pl.slug,r.status FROM pages p JOIN page_revisions r ON r.page_id=p.id JOIN page_localizations pl ON pl.page_id=p.id AND pl.language_code='pt' WHERE r.status='draft' ORDER BY r.created_at DESC")->fetchAll(PDO::FETCH_ASSOC); }
 public function published(): array { return $this->db->query("SELECT p.id,r.title,pl.slug,r.number FROM pages p JOIN page_localizations pl ON pl.page_id=p.id AND pl.language_code='pt' JOIN page_revisions r ON r.id=pl.published_revision_id ORDER BY r.published_at DESC")->fetchAll(PDO::FETCH_ASSOC); }
 public function createRevision(string $pageId): ?string { $published=$this->db->prepare("SELECT r.* FROM page_localizations pl JOIN page_revisions r ON r.id=pl.published_revision_id WHERE pl.page_id=:page AND pl.language_code='pt'"); $published->execute(['page'=>$pageId]); $source=$published->fetch(PDO::FETCH_ASSOC); if($source===false) return null; $existing=$this->db->prepare("SELECT id FROM page_revisions WHERE page_id=:page AND status='draft'"); $existing->execute(['page'=>$pageId]); if($id=$existing->fetchColumn()) return $id; $new='revision-'.bin2hex(random_bytes(8)); $now=gmdate('c'); $number=(int)$this->db->query("SELECT COALESCE(MAX(number),0)+1 FROM page_revisions WHERE page_id=".$this->db->quote($pageId))->fetchColumn(); $this->db->beginTransaction(); try { $this->db->prepare("INSERT INTO page_revisions (id,page_id,language_code,number,status,title,summary,created_at) VALUES (:id,:page,'pt',:number,'draft',:title,:summary,:created)")->execute(['id'=>$new,'page'=>$pageId,'number'=>$number,'title'=>$source['title'],'summary'=>$source['summary'],'created'=>$now]); $blocks=$this->db->prepare('SELECT type,position,data FROM blocks WHERE page_revision_id=:revision ORDER BY position'); $blocks->execute(['revision'=>$source['id']]); $copy=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)'); foreach($blocks->fetchAll(PDO::FETCH_ASSOC) as $block) $copy->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$new,'type'=>$block['type'],'position'=>$block['position'],'data'=>$block['data']]); $this->db->commit(); return $new; } catch(\Throwable $e) { $this->db->rollBack(); throw $e; } }
 public function draft(string $pageId): ?array { $statement=$this->db->prepare("SELECT p.id AS page_id,pl.slug,r.id AS revision_id,r.title,r.summary FROM pages p JOIN page_localizations pl ON pl.page_id=p.id AND pl.language_code='pt' JOIN page_revisions r ON r.page_id=p.id WHERE p.id=:page AND r.status='draft' ORDER BY r.number DESC LIMIT 1"); $statement->execute(['page'=>$pageId]); $page=$statement->fetch(PDO::FETCH_ASSOC); if($page===false)return null; $blocks=$this->db->prepare('SELECT type,data FROM blocks WHERE page_revision_id=:revision ORDER BY position'); $blocks->execute(['revision'=>$page['revision_id']]); $page['body']='';$page['code']='';foreach($blocks->fetchAll(PDO::FETCH_ASSOC) as $block){$data=json_decode($block['data'],true);if($block['type']==='text')$page['body']=$data['body']??'';if($block['type']==='code')$page['code']=$data['code']??'';}return $page; }
 public function updateDraft(string $pageId,string $title,string $summary,string $body,string $code): void { $draft=$this->draft($pageId);if($draft===null)return; $this->db->beginTransaction();try{$this->db->prepare('UPDATE page_revisions SET title=:title,summary=:summary WHERE id=:id')->execute(['title'=>$title,'summary'=>$summary,'id'=>$draft['revision_id']]);$this->db->prepare('DELETE FROM blocks WHERE page_revision_id=:revision')->execute(['revision'=>$draft['revision_id']]);$add=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$draft['revision_id'],'type'=>'text','position'=>1,'data'=>json_encode(['body'=>$body],JSON_UNESCAPED_UNICODE)]);if($code!=='')$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$draft['revision_id'],'type'=>'code','position'=>2,'data'=>json_encode(['language'=>'advpl','code'=>$code],JSON_UNESCAPED_UNICODE)]);$this->db->commit();}catch(\Throwable $e){$this->db->rollBack();throw $e;} }
 public function createTranslation(string $pageId,string $language,string $slug): ?string { if(!in_array($language,['en','es'],true))return null;$source=$this->db->prepare("SELECT r.* FROM page_localizations pl JOIN page_revisions r ON r.id=pl.published_revision_id WHERE pl.page_id=:page AND pl.language_code='pt'");$source->execute(['page'=>$pageId]);$base=$source->fetch(PDO::FETCH_ASSOC);if($base===false)return null;$exists=$this->db->prepare('SELECT 1 FROM page_localizations WHERE page_id=:page AND language_code=:language');$exists->execute(['page'=>$pageId,'language'=>$language]);if($exists->fetchColumn())return null;$revision='revision-'.bin2hex(random_bytes(8));$number=(int)$this->db->query("SELECT COALESCE(MAX(number),0)+1 FROM page_revisions WHERE page_id=".$this->db->quote($pageId))->fetchColumn();$now=gmdate('c');$this->db->beginTransaction();try{$this->db->prepare('INSERT INTO page_localizations (page_id,language_code,slug) VALUES (:page,:language,:slug)')->execute(['page'=>$pageId,'language'=>$language,'slug'=>$slug]);$this->db->prepare("INSERT INTO page_revisions (id,page_id,language_code,number,status,title,summary,created_at) VALUES (:id,:page,:language,:number,'draft',:title,:summary,:created)")->execute(['id'=>$revision,'page'=>$pageId,'language'=>$language,'number'=>$number,'title'=>$base['title'],'summary'=>$base['summary'],'created'=>$now]);$blocks=$this->db->prepare('SELECT type,position,data FROM blocks WHERE page_revision_id=:revision');$blocks->execute(['revision'=>$base['id']]);$add=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');foreach($blocks->fetchAll(PDO::FETCH_ASSOC)as$block)$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$revision,'type'=>$block['type'],'position'=>$block['position'],'data'=>$block['data']]);$this->db->commit();return $revision;}catch(\Throwable$e){$this->db->rollBack();throw$e;} }
 public function localizedDraft(string $pageId,string $language): ?array {$s=$this->db->prepare("SELECT p.id AS page_id,pl.slug,r.id AS revision_id,r.title,r.summary FROM pages p JOIN page_localizations pl ON pl.page_id=p.id AND pl.language_code=:language JOIN page_revisions r ON r.page_id=p.id AND r.language_code=:language WHERE p.id=:page AND r.status='draft' ORDER BY r.number DESC LIMIT 1");$s->execute(['page'=>$pageId,'language'=>$language]);$page=$s->fetch(PDO::FETCH_ASSOC);if($page===false)return null;$page['language']=$language;$b=$this->db->prepare('SELECT type,data FROM blocks WHERE page_revision_id=:revision ORDER BY position');$b->execute(['revision'=>$page['revision_id']]);$page['body']='';$page['code']='';foreach($b->fetchAll(PDO::FETCH_ASSOC)as$block){$data=json_decode($block['data'],true);if($block['type']==='text')$page['body']=$data['body']??'';if($block['type']==='code')$page['code']=$data['code']??'';}return$page;}
 public function updateLocalizedDraft(string $pageId,string $language,string $title,string $summary,string $body,string $code):void{$draft=$this->localizedDraft($pageId,$language);if($draft===null)return;$this->db->beginTransaction();try{$this->db->prepare('UPDATE page_revisions SET title=:title,summary=:summary WHERE id=:id')->execute(['title'=>$title,'summary'=>$summary,'id'=>$draft['revision_id']]);$this->db->prepare('DELETE FROM blocks WHERE page_revision_id=:revision')->execute(['revision'=>$draft['revision_id']]);$add=$this->db->prepare('INSERT INTO blocks (id,page_revision_id,type,position,data) VALUES (:id,:revision,:type,:position,:data)');$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$draft['revision_id'],'type'=>'text','position'=>1,'data'=>json_encode(['body'=>$body],JSON_UNESCAPED_UNICODE)]);if($code!=='')$add->execute(['id'=>'block-'.bin2hex(random_bytes(8)),'revision'=>$draft['revision_id'],'type'=>'code','position'=>2,'data'=>json_encode(['language'=>'advpl','code'=>$code],JSON_UNESCAPED_UNICODE)]);$this->db->commit();}catch(\Throwable$e){$this->db->rollBack();throw$e;}}
 public function publishLocalized(string $pageId,string $language):void{$s=$this->db->prepare("SELECT id FROM page_revisions WHERE page_id=:page AND language_code=:language AND status='draft' ORDER BY number DESC LIMIT 1");$s->execute(['page'=>$pageId,'language'=>$language]);$revision=$s->fetchColumn();if(!$revision)return;$this->db->prepare("UPDATE page_revisions SET status='published',published_at=:now WHERE id=:id")->execute(['now'=>gmdate('c'),'id'=>$revision]);$this->db->prepare('UPDATE page_localizations SET published_revision_id=:revision WHERE page_id=:page AND language_code=:language')->execute(['revision'=>$revision,'page'=>$pageId,'language'=>$language]);}
}
