<?php
declare(strict_types=1);
namespace UsinaDocs\Core\Tests;
use PHPUnit\Framework\TestCase;
use Slim\Psr7\Factory\ServerRequestFactory;
use UsinaDocs\Core\AppFactory;
use UsinaDocs\Core\Content\ReusableArtifactService;
use UsinaDocs\Core\Content\EditorialService;
use UsinaDocs\Core\Content\PublishedPageRepository;
use UsinaDocs\Core\Infrastructure\Database;
use UsinaDocs\Core\Infrastructure\Schema;
final class ReusableArtifactEditorTest extends TestCase {
 private string $path;
 protected function setUp():void{$this->path=sys_get_temp_dir().DIRECTORY_SEPARATOR.'usinadocs-artifact-editor-'.bin2hex(random_bytes(8)).'.sqlite';$db=Database::connect($this->path);Schema::migrate($db,dirname(__DIR__));Schema::seed($db);$_SESSION=['user'=>['role'=>'administrator']];}
 protected function tearDown():void{$_SESSION=[];if(is_file($this->path))@unlink($this->path);}
 public function test_artifact_has_a_versioned_draft_and_published_revision():void{$service=new ReusableArtifactService(Database::connect($this->path));$id=$service->create('aviso-seguranca','notice','Aviso de segurança','Aviso reutilizável.',['body'=>'Use proteção.']);self::assertSame('draft',$service->catalog()[0]['status']);$service->publish($id);self::assertSame('published',$service->catalog()[0]['status']);$service->createRevision($id);$draft=$service->draft($id);self::assertNotNull($draft);self::assertSame(2,$draft['number']);self::assertSame('Use proteção.',$draft['data']['body']);}
 public function test_artifact_editor_is_available_from_the_admin_panel():void{$app=AppFactory::create(dirname(__DIR__),$this->path);$_SESSION=['user'=>['role'=>'administrator']];$admin=$app->handle((new ServerRequestFactory())->createServerRequest('GET','/admin'));self::assertStringContainsString('Artefatos reutilizáveis',(string)$admin->getBody());$editor=$app->handle((new ServerRequestFactory())->createServerRequest('GET','/admin/artifacts/new'));self::assertSame(200,$editor->getStatusCode());$body=(string)$editor->getBody();self::assertStringContainsString('Editor de conteúdo',$body);self::assertStringContainsString('<strong>Artefato</strong>',$body);}
 public function test_a_published_page_keeps_the_exact_artifact_revision():void{$db=Database::connect($this->path);$artifacts=new ReusableArtifactService($db);$artifactId=$artifacts->create('aviso-compartilhado','notice','Aviso compartilhado','', ['body'=>'Primeira versão']);$artifacts->publish($artifactId);$pages=new EditorialService($db);$pageId=$pages->create('Página com artefato','pagina-com-artefato','','','','','article');$pages->replaceDraftBlocks($pageId,'pt',[['type'=>'text','data'=>['body'=>'Introdução']],['type'=>'reusable_artifact','data'=>['artifact_id'=>$artifactId]]]);$pages->publish($pageId);$artifacts->createRevision($artifactId);$artifacts->updateDraft($artifactId,'Aviso compartilhado','',['body'=>'Segunda versão']);$artifacts->publish($artifactId);$page=(new PublishedPageRepository($db))->findByLocalizedSlug('pt','pagina-com-artefato');self::assertSame('notice',$page['blocks'][1]['type']);self::assertSame('Primeira versão',$page['blocks'][1]['data']['body']);self::assertSame(1,$page['blocks'][1]['data']['_artifact']['revision']);$usages=$artifacts->usages($artifactId);self::assertCount(1,$usages);self::assertSame('outdated',$usages[0]['artifact_status']);self::assertSame(1,$usages[0]['pinned_revision_number']);self::assertSame(2,$usages[0]['current_revision_number']);}
 public function test_a_reusable_artifact_satisfies_a_required_model_type():void{$db=Database::connect($this->path);$artifacts=new ReusableArtifactService($db);$artifactId=$artifacts->create('fonte-oficial','reference','Fonte oficial','',['title'=>'Usina Docs','url'=>'https://example.test']);$artifacts->publish($artifactId);$pages=new EditorialService($db);$pageId=$pages->create('Página','pagina-referencia','','','','','reference');$pages->replaceDraftBlocks($pageId,'pt',[['type'=>'text','data'=>['body'=>'Texto']],['type'=>'reusable_artifact','data'=>['artifact_id'=>$artifactId]]]);self::assertSame([],$pages->missingRequiredArtifacts($pageId));}
 public function test_an_english_page_resolves_the_published_english_artifact():void{$db=Database::connect($this->path);$artifacts=new ReusableArtifactService($db);$artifactId=$artifacts->create('aviso-idioma','notice','Aviso','',['body'=>'Conteúdo em português']);$artifacts->publish($artifactId);$artifacts->createTranslation($artifactId,'en');$artifacts->updateTranslationDraft($artifactId,'en','Notice','',['body'=>'Content in English']);$artifacts->publishTranslation($artifactId,'en');$english=$artifacts->publishedCatalog('en');self::assertCount(1,$english);self::assertSame('Notice',$english[0]['title']);$pages=new EditorialService($db);$pages->createTranslation('page-welcome','en','welcome');$pages->replaceDraftBlocks('page-welcome','en',[['type'=>'reusable_artifact','data'=>['artifact_id'=>$artifactId,'artifact_revision_id'=>$english[0]['revision_id']]]]);$pages->publishLocalized('page-welcome','en');$page=(new PublishedPageRepository($db))->findByLocalizedSlug('en','welcome');self::assertSame('Content in English',$page['blocks'][0]['data']['body']);$artifacts->createTranslationRevision($artifactId,'en');self::assertSame(2,$artifacts->translationDraft($artifactId,'en')['number']);}
}
